server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/db_law?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  aop:
    auto: true
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
#关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update  # 后面用update
    show-sql: true